name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ssh.lolipop.jp
          username: boo.jp-daysweet
          port: 2222
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/web/daysweet.boo.jp/sample/htdocs/
            git pull origin main