name: lolipop

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@3.0.0
        with:
          ftp-server: ftp.lolipop.jp
          ftp-username: boo.jp-daysweet
          ftp-password: ABcd1234
          git-ftp-args: --remote-root /
          local-dir: public
